movierecomend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from movie import views
#用于前后端连接
urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", views.index, name="index"),
                  path("login/", views.login, name="login"),
                  path("register/", views.register, name="register"),
                  path("logout/", views.logout, name="logout"),
                  path("all_movie/", views.index, name="all_movie"),
                  path("movie/<int:movie_id>/", views.movie, name="movie"),
                  path("score/<int:movie_id>/", views.score, name="score"),
                  path("comment/<int:movie_id>/", views.make_comment, name="comment"),
                  path("like_comment/<int:comment_id>/<int:movie_id>/", views.like_comment, name="like_comment"),
                  path("unlike_comment/<int:comment_id>/<int:movie_id>/", views.unlike_comment, name="unlike_comment"),
                  path("collect/<int:movie_id>/", views.collect, name="collect"),
                  path("decollect/<int:movie_id>/", views.decollect, name="decollect"),
                  path("personal/", views.personal, name="personal"),
                  path("mycollect/", views.mycollect, name="mycollect"),
                  path("my_comments/", views.my_comments, name="my_comments"),
                  path("my_rate/", views.my_rate, name="my_rate"),
                  path("delete_comment/<int:comment_id>", views.delete_comment, name="delete_comment"),
                  path("delete_rate/<int:rate_id>", views.delete_rate, name="delete_rate"),
                  path("hot_movie/", views.hot_movie, name="hot_movie"), # 收藏最多
                  path("most_view/", views.most_view, name="most_view"),
                  path("most_mark/", views.most_mark, name="most_mark"),
                  path("latest_movie/", views.latest_movie, name="latest_movie"),
                  # path("mark_sort/", views.mark_sort, name="mark_sort"),
                  path("search/", views.search, name="search"),
                  path("all_tags/", views.all_tags, name="all_tags"),
                  path("one_tag/<int:one_tag_id>/", views.one_tag, name="one_tag"),
                  path("choose_tags/", views.choose_tags, name="choose_tags"),
                  path("director_movie/<str:director_name>", views.director_movie, name="director_movie"),
                  path("user_recommend/", views.user_recommend, name="user_recommend"),#用户推荐
                  path("item_recommend/", views.item_recommend, name="item_recommend"),#物品推荐
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

admin.site.site_header = '推荐系统后台管理'
admin.site.index_title = '首页-推荐系统'
admin.site.site_title = '推荐系统'

movie/models.py
'''
用户对电影的打分数据，以及对电影的评论模型的建立。
'''
from datetime import datetime
from datetime import date
from django.db import models
from django.db.models import Avg
from django.db.models.fields.files import FileField
from itertools import chain
#数据库表
class User(models.Model):
    username = models.CharField(max_length=255, unique=True, verbose_name="账号")#unique唯一（不重复）
    password = models.CharField(max_length=255, verbose_name="密码")
    email = models.EmailField(verbose_name="邮箱")
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "用户"
        verbose_name = "用户"

    def __str__(self):
        return self.username


class Tags(models.Model):
    name = models.CharField(max_length=255, verbose_name="标签", unique=True)

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = "标签"

    def __str__(self):
        return self.name


class UserTagPrefer(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, verbose_name="用户id",
    )
    tag = models.ForeignKey(Tags, on_delete=models.CASCADE, verbose_name='标签名')
    score = models.FloatField(default=0)

    class Meta:
        verbose_name = "用户偏好"
        verbose_name_plural = "偏好"

    def __str__(self):
        return self.user.username + str(self.score)


class Movie(models.Model):
    tags = models.ManyToManyField(Tags, verbose_name='标签', blank=True)#多对多关系
    collect = models.ManyToManyField(User, verbose_name="收藏者", blank=True)
    name = models.CharField(verbose_name="电影名称", max_length=255, unique=True)
    director = models.CharField(verbose_name="导演名称", max_length=255)
    country = models.CharField(verbose_name="国家", max_length=255)
    years = models.DateField(verbose_name='上映日期')
    leader = models.CharField(verbose_name="主演", max_length=1024)
    d_rate_nums = models.IntegerField(verbose_name="豆瓣评价数")
    d_rate = models.CharField(verbose_name="豆瓣评分", max_length=255)
    intro = models.TextField(verbose_name="描述")
    num = models.IntegerField(verbose_name="浏览量", default=0)
    origin_image_link = models.URLField(verbose_name='豆瓣图片地址', max_length=255, null=True)
    image_link = models.FileField(verbose_name="封面图片", max_length=255, upload_to='movie_cover')
    imdb_link = models.URLField(null=True)

    @property
    def movie_rate(self):
        movie_rate = Rate.objects.filter(movie_id=self.id).aggregate(Avg('mark'))['mark__avg']
        return movie_rate or '无'

    class Meta:
        verbose_name = "电影"
        verbose_name_plural = "电影"

    def __str__(self):
        return self.name

    def to_dict(self, fields=None, exclude=None):
        opts = self._meta
        data = {}
        for f in chain(opts.concrete_fields, opts.private_fields, opts.many_to_many):
            if exclude and f.name in exclude:
                continue
            if fields and f.name not in fields:
                continue
            value = f.value_from_object(self)
            if isinstance(value, date):
                value = value.strftime('%Y-%m-%d')
            elif isinstance(f, FileField):
                value = value.url if value else None
            data[f.name] = value
        return data

#用户对电影打分数据
class Rate(models.Model):
    movie = models.ForeignKey(
        Movie, on_delete=models.CASCADE, blank=True, null=True, verbose_name="电影id"
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True, verbose_name="用户id",
    )
    mark = models.FloatField(verbose_name="评分")
    create_time = models.DateTimeField(verbose_name="发布时间", auto_now_add=True)

    @property
    def avg_mark(self):
        average = Rate.objects.all().aggregate(Avg('mark'))['mark__avg']#求平均分
        return average

    class Meta:
        verbose_name = "评分信息"
        verbose_name_plural = verbose_name

#电影评论表
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="用户")#外建关联
    content = models.CharField(max_length=255, verbose_name="内容")
    create_time = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="电影")

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name


class LikeComment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, verbose_name='评论')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')

    class Meta:
        verbose_name = "评论点赞"
        verbose_name_plural = verbose_name

movie/views.py
import json
import random
from functools import wraps

from django.core.cache import cache
from django.core.paginator import Paginator
from django.db.models import Q, Count
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.renderers import JSONRenderer

from movie_it.cache_keys import USER_CACHE, ITEM_CACHE
from movie_it.recommend_movies import recommend_by_user_id, recommend_by_item_id
from .forms import *


def movies_paginator(movies, page):
    paginator = Paginator(movies, 12)
    if page is None:
        page = 1
    movies = paginator.page(page)
    return movies


# from django.urls import HT
# json response
class JSONResponse(HttpResponse):
    def __init__(self, data, **kwargs):
        content = JSONRenderer().render(data)
        kwargs["content_type"] = "application/json;"
        super(JSONResponse, self).__init__(content, **kwargs)


# 登录功能
def login(request):
    if request.method == "POST":
        form = Login(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            result = User.objects.filter(username=username)
            if result:
                user = User.objects.get(username=username)
                if user.password == password:
                    request.session["login_in"] = True
                    request.session["user_id"] = user.id
                    request.session["name"] = username
                    # 用户第一次注册，需要选标签
                    new = request.session.get('new')
                    if new:
                        tags = Tags.objects.all()
                        print('goto choose tag')
                        return render(request, 'choose_tag.html', {'tags': tags})
                    return redirect(reverse("index"))
                else:
                    return render(
                        request, "login.html", {"form": form, "message": "密码错误"}
                    )
            else:
                return render(
                    request, "login.html", {"form": form, "message": "账号不存在"}
                )
    else:
        form = Login()
        return render(request, "login.html", {"form": form})


# 注册功能
def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        error = None
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password2"]
            email = form.cleaned_data["email"]
            User.objects.create(
                username=username,
                password=password,
                email=email,
            )
            request.session['new'] = 'true'
            # 根据表单数据创建一个新的用户
            return redirect(reverse("login"))  # 跳转到登录界面
        else:
            return render(
                request, "register.html", {"form": form, "error": error}
            )  # 表单验证失败返回一个空表单到注册页面
    form = RegisterForm()
    return render(request, "register.html", {"form": form})


def logout(request):
    if not request.session.get("login_in", None):  # 不在登录状态跳转回首页
        return redirect(reverse("index"))
    request.session.flush()  # 清除session信息
    print('注销')
    return redirect(reverse("index"))


def login_in(func):  # 验证用户是否登录
    @wraps(func)
    def wrapper(*args, **kwargs):
        request = args[0]
        is_login = request.session.get("login_in")
        if is_login:
            return func(*args, **kwargs)
        else:
            return redirect(reverse("login"))

    return wrapper


# Create your views here.
def index(request):
    order =  request.POST.get("order") or request.session.get('order')
    request.session['order']=order
    if order == 'collect':
        movies = Movie.objects.annotate(collectors=Count('collect')).order_by('-collectors')
        print(movies.query)
        title = '收藏排序'
    elif order == 'rate':
        movies = Movie.objects.all().annotate(marks=Avg('rate__mark')).order_by('-marks')
        title = '评分排序'
    elif order == 'years':
        movies = Movie.objects.order_by('-years')
        title = '时间排序'
    else:
        movies = Movie.objects.order_by('-num')
        title = '热度排序'
    paginator = Paginator(movies, 8)
    new_list = Movie.objects.order_by('-years')[:8]
    current_page = request.GET.get("page", 1)
    movies = paginator.page(current_page)
    return render(request, 'items.html', {'movies': movies, 'new_list': new_list, 'title': title})

#电影详情
def movie(request, movie_id):
    movie = Movie.objects.get(pk=movie_id)
    movie.num += 1
    movie.save()
    comments = movie.comment_set.order_by("-create_time")
    user_id = request.session.get("user_id")
    movie_rate = Rate.objects.filter(movie=movie).all().aggregate(Avg('mark'))#电影评分
    if movie_rate:
        movie_rate = movie_rate['mark__avg']
    else:
        movie_rate = 0
    if user_id is not None:
        user_rate = Rate.objects.filter(movie=movie, user_id=user_id).first()
        user = User.objects.get(pk=user_id)
        is_collect = movie.collect.filter(id=user_id).first()
    return render(request, "movie.html", locals())


def search(request):  # 搜索
    if request.method == "POST":  # 如果搜索界面
        key = request.POST["search"]
        request.session["search"] = key  # 记录搜索关键词解决跳页问题
    else:
        key = request.session.get("search")  # 得到关键词
    movies = Movie.objects.filter(
        Q(name__icontains=key) | Q(intro__icontains=key) | Q(director__icontains=key)
    )  # 进行内容的模糊搜索
    page_num = request.GET.get("page", 1)
    movies = movies_paginator(movies, page_num)
    return render(request, "items.html", {"movies": movies, 'title': '搜索结果'})

#所有标签
def all_tags(request):
    tags = Tags.objects.all()
    return render(request, "all_tags.html", {'all_tags': tags})

#一个标签
def one_tag(request, one_tag_id):
    tag = Tags.objects.get(id=one_tag_id)
    movies = tag.movie_set.all()
    page_num = request.GET.get("page", 1)
    movies = movies_paginator(movies, page_num)
    return render(request, "items.html", {"movies": movies, 'title': tag.name})

#收藏最多
def hot_movie(request):
    page_number = request.GET.get("page", 1)#分页
    movies = Movie.objects.annotate(user_collector=Count('collect')).order_by('-user_collector')[:10]#查出所有电影，按收藏人数排序
    movies = movies_paginator(movies[:10], page_number)
    return render(request, "items.html", {"movies": movies, "title": "收藏最多"})#返回给items.html


# 评分最多
def most_mark(request):
    page_number = request.GET.get("page", 1)
    movies = Movie.objects.all().annotate(num_mark=Count('rate')).order_by('-num_mark')
    movies = movies_paginator(movies, page_number)
    return render(request, "items.html", {"movies": movies, "title": "评分最多"})


# 浏览最多
def most_view(request):
    page_number = request.GET.get("page", 1)
    movies = Movie.objects.annotate(user_collector=Count('num')).order_by('-num')
    movies = movies_paginator(movies, page_number)
    return render(request, "items.html", {"movies": movies, "title": "浏览最多"})

#最新电影
def latest_movie(request):
    movie_list = Movie.objects.order_by("-years")[:10]
    json_movies = [movie.to_dict(fields=['name', 'image_link', 'id', 'years', 'd_rate']) for movie in movie_list]
    return HttpResponse(json.dumps(json_movies), content_type="application/json")


# 某个导演的电影
def director_movie(request, director_name):
    page_number = request.GET.get("page", 1)
    movies = Movie.objects.filter(director=director_name)
    movies = movies_paginator(movies, page_number)
    return render(request, "items.html", {"movies": movies, "title": "{}的电影".format(director_name)})

#修改个人信息
@login_in
def personal(request):
    user = User.objects.get(id=request.session.get("user_id"))
    if request.method == "POST":
        form = Edit(instance=user, data=request.POST)
        if form.is_valid():
            form.save()
            request.session['name'] = user.username
            return render(
                request, "personal.html", {"message": "修改成功!", "form": form, 'title': '我的信息', 'user': user}
            )
        else:
            return render(
                request, "personal.html", {"message": "修改失败", "form": form, 'title': '我的信息', 'user': user}
            )
    form = Edit(instance=user)
    return render(request, "personal.html", {"user": user, 'form': form, 'title': '我的信息'})


@login_in
@csrf_exempt
def choose_tags(request):
    tags_name = json.loads(request.body)
    user_id = request.session.get('user_id')
    for tag_name in tags_name:
        tag = Tags.objects.filter(name=tag_name.strip()).first()
        UserTagPrefer.objects.create(tag_id=tag.id, user_id=user_id, score=5)
    request.session.pop('new')
    return redirect(reverse("index"))


@login_in
# 给电影进行评论
def make_comment(request, movie_id):
    user = User.objects.get(id=request.session.get("user_id"))
    movie = Movie.objects.get(id=movie_id)
    comment = request.POST.get("comment")
    Comment.objects.create(user=user, movie=movie, content=comment)
    return redirect(reverse("movie", args=(movie_id,)))


@login_in
# 展示我的评论的地方
def my_comments(request):
    user = User.objects.get(id=request.session.get("user_id"))
    comments = user.comment_set.all()
    print('comment:', comments)
    return render(request, "my_comment.html", {"item": comments})


# 给评论点赞
@login_in
def like_comment(request, comment_id, movie_id):
    user_id = request.session.get("user_id")
    LikeComment.objects.get_or_create(user_id=user_id, comment_id=comment_id)
    return redirect(reverse("movie", args=(movie_id,)))


# 取消点赞
@login_in
def unlike_comment(request, comment_id, movie_id):
    user_id = request.session.get("user_id")
    LikeComment.objects.filter(user_id=user_id, comment_id=comment_id).delete()
    return redirect(reverse("movie", args=(movie_id,)))


@login_in
def delete_comment(request, comment_id):

templates/all_tags.html
{% extends "base.html" %}
{% block main_content %}
    <div class="wrap-content">
        <div class="movie">
            <div class="row type">
                <div class="title">
                    <center><h2>电影分类</h2></center>
                </div>
            </div>
            <div class="row">
                {% for tag in all_tags %}
                    <div class="col-1-4">
                        <div class="wrap-col">
                            <div class="post">
                                <div class="view effect">
                                    <div class="mask">
                                        <a href="{% url 'one_tag' tag.id %}" class="info"></a>
                                    </div>
                                </div>
                                <div class="clear"></div>
                                <a href="{% url 'one_tag' tag.id %}"><h3>{{ tag.name }}</h3></a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/base_show.html
{% extends 'base.html' %}
{% block main_content %}
    <table class="table">
        <thead>
        <tr>
            {% block th_name %}
            {% endblock %}
        </tr>
        </thead>
        <tbody>
        {% for i in item %}
            <div class="modal" id="confirm-modal">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-footer">
                        <div class="row">
                            <div class="col-md-6">
                                                           <button type="button" class="btn btn-block btn-default" data-dismiss="modal">不确认</button>
                            </div>
                            <div class="col-md-6">
                                   {% block modal %}
                            {% endblock %}
                            </div>
                        </div>

                        </div>
                    </div>
{#                </div>#}
            </div>
            <tr>
                {% block th_value %}
                {% endblock %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <!-- Button trigger modal -->
    <!-- Modal -->
{% endblock %}

templates/choose_tag.html
{% extends 'base.html' %}
{% block main_content %}
    <h2 align="center"> 选择你喜欢的标签</h2>
    <div class="row">
        {% for tag in tags %}
            <div class="col-md-2">
                <label class="tags-input h2"><span class="label label-warning">{{ tag.name }}</span> </label>
            </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-3" style="margin-top: 100px">
            <button class="btn btn-block btn-success" style="color: white"> 提交</button>
        </div>
    </div>
{% endblock %}

{% block bottom-js %}
    <script>
        var items = [];
        $("label").each(function (index) {
            let toggle = false;
            $(this).on("click", function () {
                console.log(toggle);
                toggle = !toggle;
                if (toggle === true) {
                    items.push($(this).text());
                    $(this).children('span').addClass('label-danger');

                } else
                //删除元素
                {
                    console.log("false");
                    items.splice(items.indexOf($(this).text()), 1);
                    $(this).children('span').removeClass('label-danger');
                }
                console.log(items);
            });
        });
        $('button').click(function () {
            $.ajax({
                url: '/choose_tags/',
                type: 'POST',
                contentType: 'application/json; charset=utf-8',
                data: JSON.stringify(items),
                {#返回的数据类型#}
                dataType: 'html',
                success: function (result) {
                    alert("选择成功!");
                    var newDoc = document.open("text/html", "replace");
                    newDoc.write(result);
                    newDoc.close();
                    {#$(html).html(result);#}
                },
                fail: function (xhr, textStatus, errorThrown) {
                    alert('request failed');
                },
                error: function (jqXHR, exception) {
                    console.log(jqXHR.status);
                    console.log(exception);
                }
            });
        })
    </script>

{% endblock %}

templates/movie.html
{% extends "base.html" %}
{% load grav_tag %}
{% load is_like %}
{% block main_content %}
    <div class="wrap-content">
        <article>
            <div class="art-header">
                <div class="row">
                    <div class="col-md-3 " style="margin-bottom: 10px ;margin-top: 10px">
                        <img src="{{ MEDIA_URL }}{{ movie.image_link }}"/>
                    </div>
                    <div class="col-md-9">
                        <div class="wrap-col" style="overflow: auto">
                            <ul class="movie-info" style="overflow: auto">
                                <div class="row">
                                    <div class="col-md-6">
                                        <p>电影名: <a href="#">{{ movie.name }}</a></p>
                                    </div>
                                    <div class="col-md-6">
                                        <p>上映日期: <a href="#">{{ movie.years }}</a></p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <p>导演: <a href="#">{{ movie.director }}</a></p>
                                    </div>
                                    <div class="col-md-6">
                                        <p>主演: <a href="#">{{ movie.leader |slice:30 }}...</a></p>
                                    </div>
                                </div>
                                <li>
                                    <div class="row">
                                        <div class="col-1-3">
                                            <a target="_blank" style="display: inline-block; margin-left: 15px" class="btn-lg btn-success" href="https://www.idybee.com/?post_type=post&s={{ movie.name }}">前往观看</a>
                                        </div>
                                        <div class="col-1-3">
                                            {% if is_collect %}
                                                <a class="btn-lg btn-warning" style="display: inline-block" href="{% url 'decollect' movie.id %}">取消收藏</a>
                                            {% else %}
                                                <a class="btn-lg btn-primary" style="display: inline-block" href="{% url 'collect' movie.id %}">点击收藏</a>{% endif %}
                                        </div>
                                        <div class="col-1-3">
                                            <h2 style="display: inline"> 收藏人数:{{ movie.collect.count }} </h2>
                                        </div>
                                        {#                                            <a style="display: inline-block" class="btn-lg btn-primary" href="{% url 'collect' movie.id %}">收藏</a>#}
                                    </div>
                                <li>
                                </li>
                                <li style="margin-top: 20px"><p style="display: inline-block; margin-right: 15px">豆瓣评分: <a href="#">{{ movie.d_rate }}</a></p>
                                    <p style="display: inline-block">标签： {% for tag in movie.tags.all %}  <a href="{% url 'one_tag' tag.id %}">{{ tag.name }}</a>{% endfor %}</p>
                                </li>
                                <li style="margin-top: 20px">
                                    {% if user_rate is not None %}
                                        <h4>您已经进行打分: {{ user_rate.mark }}</h4>
                                    {% else %}
                                        <form action="{% url 'score' movie.id %}" method="post">
                                            {% csrf_token %}
                                            <p style="display: inline-block;"> 添加评分</p>
                                            <select name="score">
                                                <option>1.0</option>
                                                <option>2.0</option>
                                                <option>3.0</option>
                                                <option>4.0</option>
                                                <option>5.0</option>
                                            </select>
                                            <button type="submit" class="button bt1">提交</button>
                                        </form>
                                    {% endif %}
                                </li>
                                                            <div class="clear"></div>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
                        <div class="clear"></div>
            <div class="art-content">
                                <div class="clear"></div>
                <p>{{ movie.intro }}</p>
                <div class="clear"></div>
            </div>
        </article>
        <div class="widget wid-related">
            <div class="wid-header">
                <div class="row">
                    <div class="col-md-9">
                        <h5>基于物品推荐</h5>
                    </div>
                    <div class="col-md-3">
                        <button class="button bt1" onclick="get_item_recommend()">换一批</button>
                    </div>
                </div>
            </div>
            <div class="wid-content">
                <div class="row" id="item-recommend">
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="row">
            <div class="col-md-9">
                <form role="form" action="{% url 'comment' movie.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input placeholder="快来说说点什么吧" class="form-control" name="comment" cols="10" rows="10">
                    </div>
                    <div class="form-group">
                        <button type="submit" style="float: right;" class="btn-lg btn-success">提交评论</button>
                    </div>
                </form>
            </div>
            <div class="row">
                <div class="col-md-9">
                    <h2 style="border-bottom: dashed #fcab2b 1px; padding-bottom: 10px">评论</h2>
                    <div class="item-list">
                        <ul>
                            {% for i in comments %}
                                <li class="list-item">
                                    <div class="avartar">
                                        <a><img src='{{ request.user.email|gravatar:"75" }}'> </a>
                                    </div>
                                    <div class="list-info">
                                        <p>{{ i.content }}</p>
                                        {{ i.user.username }} 发表于{{ i.create_time }} 推荐
                                    </div>
                                    {#                                    {% if  i.user | is_like:i.user.id %}#}
                                    {#                                        <a href="{% url 'unlike_comment' i.id movie.id %}" class="recommend-link"><span class="fa fa-lg fa-thumbs-up"#}
                                    {#                                    {% else %}#}
                                    <a href="{% url 'like_comment' i.id movie.id %}" class="recommend-link"><span class="fa fa-lg fa-thumbs-up">({{ i.likecomment_set.count }})</span></a>
                                    {#                                    {% endif %}#}
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block bottom-js %}
    <script>
        function get_item_recommend() {
            $.ajax({
                url: '/item_recommend/',
                type: 'GET',
                success: function (result) {
                    var html = "";
                    var array_length = result.length;
                    for (var i = 0; i < array_length; i++) {
                        html += `<div class="col-1-3"><div class="wrap-col">` +
                            `<a href="/movie/${result[i].id}"><img src="${result[i].image_link}"/></a>` +
                            `<a href="/movie/${result[i].id}"><h4>${result[i].name}</h4></a></div></div>`;
                    }
                    $('#item-recommend').html(html);
                },
                fail: function (xhr, textStatus, errorThrown) {
                    alert('request failed');
                },
                error: function (jqXHR, exception) {
                    console.log(jqXHR.status);
                    console.log(exception);
                }
            });
        }

        get_item_recommend();
    </script>


{% endblock %}

templates/my_comment.html
{% extends "base_show.html" %}
{% block th_name %}
    <th>电影名</th>
    <th>评论内容</th>
    <th>评论时间</th>
    <th>删除</th>
{% endblock %}
{% block modal %}
    <a class="btn btn-primary btn-block" href="{% url 'delete_comment' i.id %}">确认</a>

{% endblock %}
{% block th_value %}
    <td>{{ i.movie.name }}</td>
    <td>{{ i.content }}</td>
    <td>{{ i.create_time }}</td>
    <td><a class="btn btn-danger" data-toggle="modal" data-target="#confirm-modal">删除</a></td>
{% endblock %}